# Generated by Django 4.2.16 on 2024-11-14 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='phone_number',
            field=models.CharField(default='', max_length=17),
            preserve_default=False,
        ),
    ]
